### ISSUE TITLE
Can we send and Receive from topics 

### ISSUE THREAD

**Issue by ShanmukhJoga** [sypbiz/SockJS.NET#14]
Hi Team - Great work for awesome sockjs.net project !! I have question does this support to send or receive based on topics names , For example in the send Method:  Send("Topic name" , message);
Thanks in advance !! @doronguttman @dguttman-jacada @DenisBalan

**Comment by doronguttman** [comment]
This project was intended as a .NET client for [SockJS](https://github.com/sockjs/sockjs-client).
The SockJS protocol does not support topics inherently, however you may want to consider running [STOMP](https://stomp.github.io/stomp-specification-1.2.html) on top of it (which is quite common for such a combo).

You can also implement it yourself, e.g.:
```csharp
public class TopicMessage
{
  public string Topic {get; set;}
  public string Data {get; set;}

  internal string Serialize() => JsonConvert.Serialize(this);
}

public static class SockJsExtensions
{
  public static Task Send(this SockJs sockjs, string topic, string data) => Send(sockjs, new TopicMessage(topic, data));
  public static Task Send(this SockJs sockjs, TopicMessage message) => sockjs.Send(message.Serialize()); 
}
```

**Comment by ShanmukhJoga** [comment]
Thank you for the response , I am trying what you suggested. Similar to the above can we even subscribe to stomp clients topics as well? 
my js code: stompClient.subscribe('/user/queue/eventdata', function(message) {  })

**Comment by doronguttman** [comment]
Again, the SockJS protocol is built to pass strings (or JSON strings) only. you will have to subscribe to the `Message` event and parse it, e.g.:

```csharp
sockJs.Message += (sender, msg) =>
{
    try
    {
        var topicMessage = JsonConvert.Deserialize<TopicMessage>(msg);
        // successful deserialization -> this is a TopicMessage
        InvokeTopicEvent(topicMessage);
    }
    catch (Exception ex)
    {
        // msg cannot be deserialized as TopicMessage
       InvokeNonTopicEvent(msg);
    }
};
```

**Comment by ShanmukhJoga** [comment]
Thank you once again @doronguttman  !! 
 InvokeTopicEvent(topicMessage); 
Do we need call the same SockJs send method or any other methods to implement InvokeTopicEvent method which you mentioned or do we need to call receive methods in ClientWebSocket interface 
this._socket.ReceiveAsync(buffer, CancellationToken.None);

**Comment by doronguttman** [comment]
`InvokeTopicEvent` is just something you'd have to implement internally in your app to handle the message when it arrives

**Comment by ShanmukhJoga** [comment]
Hi @doronguttman thank you for time  below event is not capturing the subscribe event from stomp topic . I have to explicitly call this similar to what you guys implemented  for connect in sockjs file like   this.Message?.Invoke(this, subscribetopic) ,  but this will not fulfill the subscribe to topic scenario.

But is there way to subscribe to topic from sock js and get the below code automatically when we get some message on the topic.

sockJs.Message += (sender, msg) =>
{
};

**Comment by doronguttman** [comment]
@ShanmukhJoga This is way outside of the scope of this project. I'll be more than happy to help with your specific project elsewhere. Feel free to provide a link to a repository with an [MRE](https://stackoverflow.com/help/minimal-reproducible-example).
I also recommend you create an issue in that repo and we can continue the discussion there.

**Comment by ShanmukhJoga** [comment]
@doronguttman any help on this greatly appreciated !!  https://github.com/ShanmukhJoga/.Net-Stomp-client-Example.git

**Comment by ShanmukhJoga** [comment]
@doronguttman Thank you my friend , I finally found way to connect to Stomp server using your sock js .net !!Amazing and thank you for responding to my questions !!Hope we can see this project in Nugget soon !!

 await sockJs.Send("CONNECT\naccept-version:1.0,1.1,2.0\n\n\x00\n");
  await sockJs.Send("SUBSCRIBE\nid:sub-0\ndestination:/user/queue/topicname\n\n\0");
await sockJs.Send("SEND\ndestination:/app/topicname\ncontent-length:\n\n"payload to be sent" \n\n\0");

After calling this I was able to get messages on below code:
  sockJs.Message += async (sender, msg) =>
                {
//Read messages from server from msg string
                 };

**Comment by doronguttman** [comment]
Good job! I'm using STOMP as well, so I may open-source my STOMP implementation.
The SockJs.NET lib has actually been nuget-ed by someone else, but it is the v1. I have asked that person to remove the package as it is taking the namespace. Hopefully I will be able to publish as well

**Comment by kall2sollies** [comment]
Hi,
I hopefully found this thread as I also need to use your lib and subscribe to a STOMP destination.
Since you're stuck with publishing a Nuget package, I had to push your code to my private Azure devops repo, in order to use it as a private nuget package.
So please let me know when you manage to publish it, so that I can remove mine.

**Comment by doronguttman** [comment]
we're waiting on a PR for the nuget package code. feel free to submit one if you have the time

**Comment by kall2sollies** [comment]
I'm running a heavy sprint, so for now, I'll rely on @ShanmukhJoga solution, but when it's refactoring time, I'll try !

**Comment by kall2sollies** [comment]
Actually I switched my source copy to a fork of yours. So if a come with a nice implementation of STOMP destinations, it's gonna be easy for me to PR.

**Comment by doronguttman** [comment]
@kall2sollies see: https://github.com/sypbiz/SockJS.NET/issues/15
