### ISSUE TITLE
Private key password

### ISSUE THREAD

**Issue by appgurung** [sypbiz/SockJS.NET#22]
Please I need urgent assistance.

I was trying to install syp.biz.SockJS.NET.pfx file. I need the correct password to enter to enable me install the key file.

Please kindly help me out here.

**Comment by doronguttman** [comment]
Did you try downloading the NuGet package?

https://www.nuget.org/packages/syp.biz.SockJS.NET.Client

**Comment by doronguttman** [comment]
no response...
