### ISSUE TITLE
Use C# style events

### ISSUE THREAD

**Issue by doronguttman** [sypbiz/SockJS.NET#4]
Hey, I had one other really silly question is it possible to define the event handlers like this?

sockJs.OnMessage += onMessage;
In lieu of:
sockJs.AddEventListener("message" (sender, e) => .. );

??

_Originally posted by @zerocarbthirty in https://github.com/sypbiz/SockJS.NET/issues/2#issuecomment-559279673_

**Comment by doronguttman** [comment]
This project was a direct port of the JavaScript library and kept most of the code as-is in order to provide a C# solution as quickly as possible.
There is a plan to re-write the solution from the ground up in a pure-C#, object-oriented, best-practice way. This would include C# event subscription, async support and/or [reactive](https://github.com/dotnet/reactive) handlers.

I hope I can get to it ASAP and you are also welcome to contribute.

**Comment by zerocarbthirty** [comment]
I'll try. I have had a lot of issues getting up to speed with C#. Im mostly
a PHP developer. Things as simple as parsing JSON has been a whole new
world :)

**Comment by doronguttman** [comment]
resolved https://github.com/sypbiz/SockJS.NET/commit/25a9422b056bcdc7ba4256479fdf13957567d9bd
